//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopQuanAo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDonBanLe
    {
        public int MaCTHDL { get; set; }
        public int MaHDL { get; set; }
        public string MaHang { get; set; }
        public Nullable<int> MaCTHH { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public string GhiChu { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
        public virtual HoaDonBanLe HoaDonBanLe { get; set; }
    }
}
