//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopQuanAo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTiet_PhieuNhapKho
    {
        public int MaCTPN { get; set; }
        public string MaPhieuNhap { get; set; }
        public string MaHang { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<double> GiaVon { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public string MoTa { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
        public virtual PhieuNhapKho PhieuNhapKho { get; set; }
    }
}
