//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopQuanAo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHangHoa
    {
        public int MaCTHH { get; set; }
        public string MaHang { get; set; }
        public string MaMau { get; set; }
        public string MaSize { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string Hinhdaidien { get; set; }
        public string Hinh1 { get; set; }
        public string Hinh2 { get; set; }
        public string Hinh3 { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
        public virtual MauSac MauSac { get; set; }
        public virtual KichThuoc KichThuoc { get; set; }
    }
}
