//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopQuanAo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTiet_HoaDonBanSi
    {
        public string MaCTHDS { get; set; }
        public string MAHDS { get; set; }
        public string MaHang { get; set; }
        public string MauSac { get; set; }
        public string MaSize { get; set; }
        public string MaDVT { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public Nullable<double> GiamGia { get; set; }
        public Nullable<double> SoTienGiam { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DonViTinh DonViTinh { get; set; }
        public virtual KichThuoc KichThuoc { get; set; }
        public virtual HangHoa HangHoa { get; set; }
        public virtual HoaDon_BanSi HoaDon_BanSi { get; set; }
    }
}
