//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopQuanAo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonViTinh
    {
        public DonViTinh()
        {
            this.ChiTiet_HoaDonBanSi = new HashSet<ChiTiet_HoaDonBanSi>();
        }
    
        public string MaDVT { get; set; }
        public string TenDVT { get; set; }
    
        public virtual ICollection<ChiTiet_HoaDonBanSi> ChiTiet_HoaDonBanSi { get; set; }
    }
}
