//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopQuanAo
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangHoa
    {
        public HangHoa()
        {
            this.ChiTiet_HoaDonBanSi = new HashSet<ChiTiet_HoaDonBanSi>();
            this.ChiTiet_PhieuNhapKho = new HashSet<ChiTiet_PhieuNhapKho>();
            this.ChiTietHangHoas = new HashSet<ChiTietHangHoa>();
            this.ChiTietHoaDonBanLes = new HashSet<ChiTietHoaDonBanLe>();
        }
    
        public string MaHang { get; set; }
        public string TenHang { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public string MaDVT { get; set; }
        public string MaLo { get; set; }
        public string MaKho { get; set; }
        public string MaLoai { get; set; }
        public string KieuDang { get; set; }
        public string XuatXu { get; set; }
        public string NhaSanXuat { get; set; }
        public Nullable<System.DateTime> NamSanXuat { get; set; }
        public Nullable<double> GiaMua { get; set; }
        public Nullable<double> GiaBanLe { get; set; }
        public Nullable<double> GiaBanSi { get; set; }
        public Nullable<int> TrongLuong { get; set; }
        public Nullable<int> ChieuDai { get; set; }
        public Nullable<int> ChieuRong { get; set; }
        public string QuyCach { get; set; }
        public string MoTa { get; set; }
        public string DanhCho { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual ICollection<ChiTiet_HoaDonBanSi> ChiTiet_HoaDonBanSi { get; set; }
        public virtual ICollection<ChiTiet_PhieuNhapKho> ChiTiet_PhieuNhapKho { get; set; }
        public virtual ICollection<ChiTietHangHoa> ChiTietHangHoas { get; set; }
        public virtual ICollection<ChiTietHoaDonBanLe> ChiTietHoaDonBanLes { get; set; }
        public virtual Kho Kho { get; set; }
        public virtual LoaiHang LoaiHang { get; set; }
        public virtual LoHang LoHang { get; set; }
    }
}
