//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopQuanAo
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhThuc
    {
        public HinhThuc()
        {
            this.HoaDon_BanSi = new HashSet<HoaDon_BanSi>();
            this.PhieuChiTiens = new HashSet<PhieuChiTien>();
        }
    
        public string MaHT { get; set; }
        public string TenHT { get; set; }
    
        public virtual ICollection<HoaDon_BanSi> HoaDon_BanSi { get; set; }
        public virtual ICollection<PhieuChiTien> PhieuChiTiens { get; set; }
    }
}
