//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopQuanAo
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon_BanSi
    {
        public HoaDon_BanSi()
        {
            this.ChiTiet_HoaDonBanSi = new HashSet<ChiTiet_HoaDonBanSi>();
        }
    
        public string MAHDS { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<double> Chietkhau { get; set; }
        public Nullable<double> TienChietKhau { get; set; }
        public Nullable<double> Thue { get; set; }
        public Nullable<double> TongThue { get; set; }
        public string MaHT { get; set; }
        public string SoDienThoai { get; set; }
        public string LoaiKH { get; set; }
        public Nullable<int> MaNV { get; set; }
        public string MaKho { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string DiaChiGiao { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<ChiTiet_HoaDonBanSi> ChiTiet_HoaDonBanSi { get; set; }
        public virtual HinhThuc HinhThuc { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual LoaiKhachHang LoaiKhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual Kho Kho { get; set; }
    }
}
