//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopQuanAo
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.HoaDon_BanSi = new HashSet<HoaDon_BanSi>();
            this.HoaDonBanLes = new HashSet<HoaDonBanLe>();
        }
    
        public int MaKH { get; set; }
        public string TenKH { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string SoDienThoai { get; set; }
        public string LoaiKH { get; set; }
        public Nullable<int> DiemThuong { get; set; }
        public string Taikhoan { get; set; }
        public string Matkhau { get; set; }
        public Nullable<System.DateTime> NgayDK { get; set; }
    
        public virtual ICollection<HoaDon_BanSi> HoaDon_BanSi { get; set; }
        public virtual ICollection<HoaDonBanLe> HoaDonBanLes { get; set; }
        public virtual LoaiKhachHang LoaiKhachHang { get; set; }
    }
}
