//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopQuanAo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho
    {
        public Kho()
        {
            this.HangHoas = new HashSet<HangHoa>();
            this.HoaDon_BanSi = new HashSet<HoaDon_BanSi>();
        }
    
        public string MaKho { get; set; }
        public string TenKho { get; set; }
        public string NhomKho { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string DiaDiem { get; set; }
    
        public virtual ICollection<HangHoa> HangHoas { get; set; }
        public virtual ICollection<HoaDon_BanSi> HoaDon_BanSi { get; set; }
    }
}
