//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopQuanAo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiPhi
    {
        public LoaiPhi()
        {
            this.PhieuChiTiens = new HashSet<PhieuChiTien>();
        }
    
        public string MaPhi { get; set; }
        public string TenPhi { get; set; }
    
        public virtual ICollection<PhieuChiTien> PhieuChiTiens { get; set; }
    }
}
