//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopQuanAo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiThue
    {
        public LoaiThue()
        {
            this.HoaDonBanLes = new HashSet<HoaDonBanLe>();
        }
    
        public string MaThue { get; set; }
        public string TenThue { get; set; }
    
        public virtual ICollection<HoaDonBanLe> HoaDonBanLes { get; set; }
    }
}
