//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopQuanAo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiKhachHang
    {
        public LoaiKhachHang()
        {
            this.HoaDon_BanSi = new HashSet<HoaDon_BanSi>();
            this.KhachHangs = new HashSet<KhachHang>();
        }
    
        public string LoaiKH { get; set; }
        public string TenLoai { get; set; }
    
        public virtual ICollection<HoaDon_BanSi> HoaDon_BanSi { get; set; }
        public virtual ICollection<KhachHang> KhachHangs { get; set; }
    }
}
