//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopQuanAo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoHang
    {
        public LoHang()
        {
            this.HangHoas = new HashSet<HangHoa>();
            this.PhieuNhapKhoes = new HashSet<PhieuNhapKho>();
        }
    
        public string MaLo { get; set; }
        public string TenLo { get; set; }
    
        public virtual ICollection<HangHoa> HangHoas { get; set; }
        public virtual ICollection<PhieuNhapKho> PhieuNhapKhoes { get; set; }
    }
}
