//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopQuanAo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Data_QLBanQuanAoEntities1 : DbContext
    {
        public Data_QLBanQuanAoEntities1()
            : base("name=Data_QLBanQuanAoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChiTiet_HoaDonBanSi> ChiTiet_HoaDonBanSi { get; set; }
        public DbSet<ChiTiet_PhieuNhapKho> ChiTiet_PhieuNhapKho { get; set; }
        public DbSet<ChiTietHangHoa> ChiTietHangHoas { get; set; }
        public DbSet<ChiTietHoaDonBanLe> ChiTietHoaDonBanLes { get; set; }
        public DbSet<ChucVu> ChucVus { get; set; }
        public DbSet<DonViTinh> DonViTinhs { get; set; }
        public DbSet<GiamGia> GiamGias { get; set; }
        public DbSet<HangHoa> HangHoas { get; set; }
        public DbSet<HinhThuc> HinhThucs { get; set; }
        public DbSet<HoaDon_BanSi> HoaDon_BanSi { get; set; }
        public DbSet<HoaDonBanLe> HoaDonBanLes { get; set; }
        public DbSet<KhachHang> KhachHangs { get; set; }
        public DbSet<Kho> Khoes { get; set; }
        public DbSet<KichThuoc> KichThuocs { get; set; }
        public DbSet<LoaiHang> LoaiHangs { get; set; }
        public DbSet<LoaiKhachHang> LoaiKhachHangs { get; set; }
        public DbSet<LoaiPhi> LoaiPhis { get; set; }
        public DbSet<LoaiThue> LoaiThues { get; set; }
        public DbSet<LoHang> LoHangs { get; set; }
        public DbSet<MauSac> MauSacs { get; set; }
        public DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public DbSet<NhanVien> NhanViens { get; set; }
        public DbSet<PhieuChiTien> PhieuChiTiens { get; set; }
        public DbSet<PhieuNhapKho> PhieuNhapKhoes { get; set; }
    }
}
